// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ProvaSolucaoInformatica.Databases.Default.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    internal class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProvaSolucaoInformatica.Databases.Default.Entities.Cliente", b =>
            {
                b.Property<int>("Codigo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.Property<string>("Nome")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.Property<string>("Telefone")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.HasKey("Codigo");

                b.ToTable("Clientes");
            });

            modelBuilder.Entity("ProvaSolucaoInformatica.Databases.Default.Entities.Usuario", b =>
            {
                b.Property<int>("Codigo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Login")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.Property<string>("Nome")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.Property<string>("Senha")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.HasKey("Codigo");

                b.ToTable("Usuarios");
            });
#pragma warning restore 612, 618
        }
    }
}